src/main/java/flow/Enrich.java, src/main/resources/morph-enriched.xml, src/test/java/flow/TestJsonLd.java, src/test/resources/test_morph-enriched.xml
* Get rid of @-symbol of @type and @id 
* Change data.lobid.org to beta.lobid.org
=> Minor data adjustments

web/app/controllers/Application.java, web/app/controllers/Reconcile.java, web/app/views/index.scala.html, web/conf/routes, web/test/ApplicationTest.java, web/test/IntegrationTest.java
=> Initial OpenRefine reconciliation service implementation

README.textile, src/main/java/flow/Index.java
=> Update README and check file size for actually passed path

web/app/controllers/Application.java
See #66. Fixes NWBib production issue (http://lobid.org/nwbib/HT015440386).
=> Handle missing organisations, respond with 404 NOT_FOUND

src/main/resources/morph-enriched.xml
@fsteeg Index is organisations-20150908-pvb
=> add DBS addressCountry processing to morph-enriched.xml

web/app/controllers/Application.java, web/test/IntegrationTest.java
=> Pretty-print JSON responses

web/conf/context.jsonld
=> Fx telephone entry in context

src/main/resources/morph-enriched.xml, src/test/resources/test_morph-enriched.xml
=> Remove email and telephone from DBS-derived data

src/main/java/flow/Constants.java, src/main/resources/morph-enriched.xml, src/test/resources/test_morph-enriched.xml
Will resolve #90 
This pull requests also sets up staging settings for indexing and geo lookups.
=> Update source field for rs in DBS data and fix digits bug

src/main/resources/morph-enriched.xml, src/test/resources/test_morph-enriched.xml, web/conf/context.jsonld
This means basically using "label" instead of "value" for labels of notations. Fixes #117.
=> Adopt side car approach from lobid-resources

src/main/resources/morph-dbs.xml, src/test/resources/test_morph-dbs.xml
=> Replace `/` with `-` in DBS isil field, `urlencode` the rest

src/main/java/flow/Enrich.java, src/main/java/flow/EnrichSample.java, src/main/java/flow/Index.java, src/test/java/flow/TestGeoEnrich.java
=> Fix compiler warnings

web/conf/context.jsonld
See #123. Pre-requisite for adjusting http://lobid.org/download/lookup-tables/data/libtype-map.csv.
=> Add classes/types to JSON-LD context

web/app/controllers/Application.java, web/app/controllers/Index.java, web/app/views/index.scala.html
Will resolve #140 
Deployed to staging: http://test.lobid.org/organisations
=> Serve valid JSON-LD for query requests and document RDF usage

test/controllers/ApplicationTest.java, test/controllers/IntegrationTest.java
=> Update and enable integration tests in CI

app/transformation/morph-enriched.xml
=> Take only first occurence of each kind of sameAs links

app/controllers/Application.java, app/views/api.scala.html, app/views/organisation.scala.html, app/views/search.scala.html, conf/routes, public/stylesheets/main.css, test/controllers/ApplicationTest.java
=> Basic search UI

app/controllers/Application.java, app/views/organisation.scala.html, conf/routes, public/stylesheets/main.css
Create view for a single organisation
* Add parameter to specify whether organisation is to be displayed as plain JSON or rendered in HTML view
* Add template for organisation view (preliminary)
Will resolve #33
=> 33 html views organisations

app/transformation/morph-enriched.xml
=> Fix type field mapping for DBS data

app/controllers/Application.java, app/views/search.scala.html, conf/index-settings.json, public/stylesheets/main.css
=> Basic search result filtering based on term aggregations

app/controllers/Application.java, app/views/facet_map.scala.js, app/views/main.scala.html, app/views/search.scala.html, app/views/tags/facet_map.scala.html, conf/routes
=> Improve performance on index page (map with all markers)

app/controllers/Application.java, app/views/details_map.scala.js, app/views/organisation.scala.html, app/views/search.scala.html, conf/routes, public/stylesheets/main.css, test/controllers/ApplicationTest.java
Will resolve #185 
Includes some refactoring and cleanup, see commits.
@SBRitter assigning you for review when you're back next week. Will attempt the appraoch we discussed the other day with @dr0i for additional work based on longer-running pull requests (pull request against feature branch instead of master).
=> Extract details map into template

app/views/details_map.scala.js, app/views/organisation.scala.html, public/stylesheets/main.css
Use striped tables for both details on left side and in marker pop up on map in single organisation view.
Will resolve #191
=> Use striped tables in detail view (#191)

app/views/search.scala.html
=> Visual indicator and removal of current facet filters

app/controllers/Application.java, app/views/organisation.scala.html
=> Don't show details map if organisation has no geo data

app/controllers/LocationAggregation.java
=> Get aggregation organisation ID from `id` field, not `isil`

app/views/details_map.scala.js, app/views/facet_map.scala.js, conf/application.conf
* Declare markers for different types in application.conf (#188)
* Replace if-structures with call to configuration in templates (#188)
* In addition, remove uppercasing of isils in marker links (#200)
Will resolve #188 and #200
=> Extract marker configuration into application.conf

app/views/facet_map.scala.js, app/views/main.scala.html, app/views/organisation.scala.html, app/views/search.scala.html
Will resolve #203
Will resolve #204
=> Javascript map issues

app/views/facet_map.scala.js, app/views/location_details.scala.js, public/stylesheets/main.css
=> Add attribution to maps

app/controllers/Accept.java, app/controllers/Application.java, app/views/api.scala.html, app/views/facet_map.scala.js, app/views/main.scala.html, app/views/search.scala.html, conf/messages.de, conf/messages.en, test/controllers/AcceptIntegrationTest.java, test/controllers/AcceptUnitTest.java, test/controllers/ApplicationTest.java
=> Content negotiation for searches and resources

conf/index-settings.json, test/index/TestStemming.java
=> Set up stemming for German with Snowball filter

app/controllers/Application.java, app/views/organisation.scala.html
Will resolve #223
Will resolve #225
=> Fix organisation name issues

app/views/organisation.scala.html
=> Remove 'mailto:' from mail link labels

app/views/facet_map.scala.js, app/views/location_details.scala.js
Free MapQuest service has been shut down: http://goo.gl/xB0xXt
Will resolve #234
=> Replace MapQuest tiles with Wikimedia OSM tiles

app/controllers/Accept.java, app/controllers/Application.java, app/transformation/CsvExport.java, app/views/api.scala.html, app/views/organisation.scala.html, app/views/search.scala.html, build.sbt, conf/messages.de, conf/messages.en, test/controllers/AcceptIntegrationTest.java, test/controllers/AcceptUnitTest.java, test/transformation/CsvExportTest.java
=> CSV export

app/views/index.scala.html, app/views/main.scala.html, conf/messages.de, conf/messages.en, public/stylesheets/main.css
=> Move hbz logo to footer, "lobid-organisations" to nav bar

cron.sh
For crontab changes discussed today
=> Update deployment documentation for cron.sh

app/views/location_details.scala.js
Fix popup by adding locationDetails to method call of zoomDetails.
Will resolve #239
=> Display location details when popup is closed and opened up again

app/controllers/Application.java, conf/routes
=> Handle trailing slashes

app/transformation/Enrich.java, app/transformation/Helpers.java, build.sbt, test/transformation/EnrichTest.java, test/transformation/TestMorphs.java
See https://github.com/hbz/metafacture-core/commit/ea0fbaf720d4277590ce5716c22155c9f675f3e5
=> Update lobid-organisations to latest metafacture-core

app/controllers/Application.java, app/views/facet_map.scala.js, app/views/main.scala.html, app/views/search.scala.html, conf/messages.de, conf/messages.en, conf/routes
Will resolve #261 
Deployment note: this is based on 77-lookup
=> Sort result list for simple search by dist to user position

app/views/organisation.scala.html, conf/messages.de, conf/messages.en
=> Show subjects in details view

app/transformation/morph-enriched.xml
=> Adjust geonames URIs.

app/views/api.scala.html, conf/messages.de, conf/messages.en
See #65 
Deployed to staging, see http://test.lobid.org/organisations/api#jsonld
=> Add sample document with hypothes.is embed

app/views/location_details.scala.js, app/views/organisation.scala.html, conf/messages.de
Will resolve #286
Deployed to staging, see: http://test.lobid.org/organisations/DE-MUS-496911
=> Don't show label for empty fields

app/views/search.scala.html
Will resolve #285.
Deployed to staging: http://test.lobid.org/organisations/search
=> Show localized labels in popups for result list icons

app/Global.java
Will resolve #287.
Deployed to staging:
`curl -I http://test.lobid.org/organisations/api`
`curl -I --header "Accept-Language: en" http://test.lobid.org/organisations/api`
`curl -I --header "Accept-Language: de" http://test.lobid.org/organisations/api`
=> Wrap all responses to contain a Content-Language header

app/controllers/Application.java, app/views/api.scala.html, conf/routes
Will resolve #292
Deployed to staging:
http://test.lobid.org/organisations/api
http://test.lobid.org/organisations/api/de
http://test.lobid.org/organisations/api/en
=> Set up localized URLs for API documentation

app/views/api.scala.html
Will partially resolve #65 
Fixes wrong links, see https://github.com/hbz/lobid-organisations/issues/65#issuecomment-271311469
See: http://test.lobid.org/organisations/api
=> Update documentation links for current data structure

app/views/organisation.scala.html, conf/messages.de, conf/messages.en
Will resolve #299
Deployed to staging, see: http://test.lobid.org/organisations/DE-Rhn2
=> Add link to modification form at ISIL registry

app/views/index.scala.html, conf/messages.de, conf/messages.en
=> Add rudimentary licensing information.

app/controllers/Application.java, app/views/search.scala.html, conf/context.jsonld
Will partially resolve https://github.com/hbz/lobid-resources-web/issues/26
Deployed to staging, see: http://test.lobid.org/organisations/search?q=hbz&format=json
=> Use Hydra vocabulary and structure for search results

app/controllers/Application.java, app/controllers/Index.java, app/controllers/Reconcile.java, conf/routes, test/index/AggregationsTest.java
See https://github.com/hbz/lobid-resources-web/issues/26
Deployed to staging:
http://test.lobid.org/organisations/search?q=hbz&format=json (no aggregations)
http://test.lobid.org/organisations/search?q=hbz&format=json&aggregations=type,classification.label.en (supported)
http://test.lobid.org/organisations/search?q=hbz&format=json&aggregations=name (unsupported)
=> Support customizable aggregations, none as default

conf/context.jsonld, conf/morph-enriched.xml
=> Remove isPrimaryTopicOf & primaryTopic.

conf/about.jsonld
Just noticed that this also should be bilingual.
=> Make description of distribution bilingual

app/controllers/Application.java, app/controllers/Index.java, app/controllers/Reconcile.java, app/views/api.scala.html
Will resolve https://github.com/hbz/lobid-organisations/issues/313
Involved some changes and cleanup to the general index access
=> Get API documentation sample from index

conf/morph-enriched.xml
=> Add subdomain to DBpedia links.

conf/morph-enriched.xml
According to changes in https://github.com/hbz/lobid-vocabs/pull/61.
=> Adjust museum classification label

app/views/api.scala.html
=> Switch back to DE-38M as documentation example

app/controllers/Application.java, app/views/index.scala.html, conf/messages.de, conf/messages.en, conf/wikidata.sparql, public/stylesheets/main.css
Will resolve https://github.com/hbz/lobid-organisations/issues/321
=> Add random image of ISIL organization to index page

app/views/main.scala.html
Will partially resolve https://github.com/hbz/lobid/issues/323
=> Update nav bar for new landing page

app/views/api.scala.html, conf/messages.de, conf/messages.en
Will resolve https://github.com/hbz/lobid-resources/issues/279
=> Add beta note to API documentation

app/controllers/Application.java, test/controllers/AcceptUnitTest.java, test/controllers/IntegrationTest.java
Will resolve https://github.com/hbz/lobid-organisations/issues/330
=> Support suggestions response format

conf/context.jsonld
Fixes https://github.com/hbz/lobid-organisations/issues/333
=> Replace daia:provides by reverse schema:provider

app/controllers/Application.java, test/controllers/IntegrationTest.java
Will resolve https://github.com/hbz/lobid-organisations/issues/356
=> Support GET by DBS ID, redirect if ISIL exists

app/controllers/Application.java
Will resolve https://github.com/hbz/lobid-organisations/issues/360
=> Require type field for results in simple queries

app/transformation/GeoLookupMap.java, conf/application.conf
Update server location, remove query parameters, tweak logging
Will resolve https://github.com/hbz/lobid-organisations/issues/357
=> Use internal geo lookup server

app/controllers/RdfConverter.java
Is useful for lobid-organisations
=> Add :org namespace

app/views/api.scala.html, conf/messages.de, conf/messages.en
See https://github.com/hbz/lobid/issues/345
=> Remove open beta notice

app/transformation/CsvExport.java
Will resolve https://github.com/hbz/lobid-organisations/issues/324
=> Handle unexpected non-string values in CSV export

app/controllers/Application.java, app/views/organisation.scala.html, conf/messages.de, conf/messages.en
Will resolve https://github.com/hbz/lobid-organisations/issues/328
=> Return full HTML response with header and footer on 404

app/controllers/Reconcile.java
=> Fix problems with reconciliation endpoint

app/views/dataset.scala.html, app/views/index.scala.html, app/views/main.scala.html, conf/dataset.jsonld, conf/messages.de, conf/messages.en
Resolves #412 . We will probably have to fix some things for the HTML view before deploying, thus assigning @fsteeg .
=> Update dataset description

.gitignore, app/controllers/Application.java, conf/application.conf, test/controllers/ApplicationTest.java
See https://github.com/hbz/lobid-resources/issues/830
=> Avoid internal URL in JSON response

conf/context.jsonld, conf/morph-enriched.xml, test/transformation/TestTransformAll.java, test/transformation/input/sigel.xml
- expand morph rules
- add test
Resolves #421.
=> Add api description

.travis.yml, conf/morph-enriched.xml, test/index/TestJsonLd.java
Changed in https://github.com/hbz/lookup-tables/commit/4c17237
Will resolve https://github.com/hbz/lobid-organisations/issues/426
=> Update map lookup for new quoted ISILs in isil2wikidata.csv

app/views/facet_map.scala.js, app/views/index.scala.html, app/views/location_details.scala.js, public/javascripts/Leaflet.MakiMarkers.js
- use a script at lobid to proxy images
- use lobid as proxy for the tileserver
See hbz/lobid#421
=> Proxy external links

conf/morph-dbs.xml, conf/morph-enriched.xml
This data shall be have highest precedence.
See #434.
=> Use dbs geo data

app/views/index.scala.html, app/views/main.scala.html, app/views/organisation.scala.html
See https://github.com/hbz/lobid/issues/423
=> Improve accessibility for lobid-organisations

app/views/facet_map.scala.js, app/views/location_details.scala.js
- set maxZoom to 17
See https://github.com/hbz/lobid/issues/309.
Test e.g. https://test.lobid.org/organisations/DE-MUS-230419
=> Switch to use hbz' tileserver

conf/fix-enriched.fix
Related to #487
Fix broke but was not logged. This fix helps that the transformation does not break.
=> 487 broken updates

checkIfBaseDataShouldBeUpdated.sh, restart.sh
=> Add script to remind if basedump is old

.github/workflows/build.yml
Resolves #515.
See https://github.com/actions/setup-java/issues/694.
=> Add sbt in GitHub actions
