hbz/lobid-organisations

src/main/java/flow/Enrich.java
Adjust method buildUpdatePipe of class Enrich so that the last interval ends with the date of today. This should (at least partially) solve #34.
=> Fix update mechanism for Sigel data

src/main/resources/morph-dbs.xml, src/test/resources/test_morph-dbs.xml
"addressCountry" information is also inferred from DBS data now. A new .csv lookup table has been stored on the server for this purpose, containing a mapping of iso3-codes and countries (analogous to the existing iso2-code lookup table). Added test cases for countries.
The presumable switch from fully spelled countries to iso codes in our result data is going to be done in a separate ticket.
=> Infer addressCountry from DBS iso field via iso3-country-map

web/app/controllers/Application.java
Required for external access from within a browser using JavaScript
=> Set CORS header in get and search routes for JS API access

src/main/resources/morph-enriched.xml, src/test/resources/test_morph-enriched.xml
Simply rename field from DBS dump abbreviation to its destinated name.
=> Rename output field 'ema' to 'email' for DBS entries (#84)

src/main/java/flow/Index.java
See #91 (was using wrong default encoding on weywot2)
=> Make sure data is read as UTF-8 when indexing

src/main/resources/morph-enriched.xml
Removed the country formatting for Sigel addresses. Resulting format is iso2, just like in the Sigel input.
The "country-map" is still used for geo-lookup.
=> Change addressCountry format to iso2 for Sigel entries (#73)

src/main/resources/morph-enriched.xml, src/test/resources/test_morph-enriched.xml
Will resolve #110
The IDs and values for the `stocksize`, `fundertype`, and `classification` fields were combined from data in the Sigel registry (IDs) and DBS (values). This resulted in missing or inconsistent data. Instead, map Sigel IDs to their values (if we have Sigel data), or DBS values to IDs (if we have no Sigel data).
=> Don't combine stocksize, fundertype & classification sources

src/main/java/flow/Constants.java, src/main/java/flow/Enrich.java, src/main/java/flow/EnrichSample.java, src/main/java/flow/Helpers.java, src/test/java/flow/TestGeoEnrich.java
Resolves #119
Deployment note: with currently deployed parameter setup the behavior changes to skip remote geo lookup with these changes. After deployed to weywot2, update parameters in weywot1's cron to pass the additional `"http://gaia.hbz-nrw.de:7400"` parameter.
=> Make external service usage optional via command line args

src/main/resources/morph-enriched.xml
Fixes #116 (in part). The rest is done in https://github.com/hbz/lookup-tables/pull/2/commits/ecf8cd97572729c399cd57664c8b01c0e457f9ab. Both following classification adjustments in https://github.com/lobid/vocabs/commit/2ec7663d921928f85b6e7e0d255322b6cd517b15.
=> Adjust libtype-id-to-value map after SKOS changes (#116).

app/transformation/morph-enriched.xml, test/transformation/test_morph-enriched.xml
Also extracts rules to a macro to avoid further duplication.
Will resolve #146.
@dr0i Please only `+1` after review, will merge myself during production deployment.
=> Remove whitespace from url and provides fields

conf/index-settings.json, test/controllers/IntegrationTest.java, test/index/ElasticsearchTest.java, test/index/TestJsonStructure.java
Will resolve #131
Uses keyword tokenizer and lowercase filter to work with query string query's lowercasing. Update tests for tweaked behavior.
=> Set up ID analyzer for id and isil fields

app/views/organisation.scala.html
Take field classification.id as info to distinguish between types of organisations and use different Maki Markers accordingly:
Examples for testing:
* Mediathek: http://localhost:9000/organisations/DE-2168?format=html
* Archiv: http://localhost:9000/organisations/DE-479?format=html
* Denkmalpflege: http://localhost:9000/organisations/DE-1929?format=html
* Fahrbibliothek: http://localhost:9000/organisations/DE-800?format=html
* Museum: http://localhost:9000/organisations/DE-MUS-023216?format=html
* Default case: http://localhost:9000/organisations/DE-380?format=html
Maybe the symbol "bus" is not appropriate for the type "Fahrbibliothek" as this symbol is used frequently on maps for transport. Might thus lead to confusion.
Will resolve #179
=> Use different icons for different types of organisations on map in single result view

app/controllers/Application.java, app/views/details_map.scala.js, app/views/location_details.scala.js, app/views/organisation.scala.html, public/stylesheets/main.css
Handle multiple locations and postal address in different tabs such that:
* multiple maps are displayed when geo data is available for the location
* address table is displayed in that tab if NO geo data is available
* postal address is shown is separate tab if available
* no tab layout is shown if only ONE information can be displayed (either one map or one address table for a location or -- no test case found -- the postal address alone)
Will resolve #210
=> Handle multiple locations and postal address in organisation view

app/transformation/morph-sigel.xml, test/transformation/test_morph-sigel.xml
DBS ID must be made of two capital letters followed by three digits
Will resolve #237
=> Validate DBS ID format in Sigel data

app/views/api.scala.html
Will resolve #291
Inserting the actual host resulted in the issue of showing the internal hostname due to some Apache config issue (it worked for beta.lobid.org/organisations but not lobid.org/organisations). I don't think it's worth to invest time here, instead this changes the documentation to the production URL in general.
Deployed to staging: http://test.lobid.org/organisations/api
=> Consistently use production domain in API docs

app/views/organisation.scala.html, app/views/search.scala.html, conf/application.conf
Will resolve #297
See:
http://test.lobid.org/organisations/search (`Typ` facet in German version)
http://test.lobid.org/organisations/DE-2382 (`Typ` field in German version)
=> Show German type labels in search and details

conf/about.jsonld
See https://github.com/hbz/lobid-organisations/issues/255
As one can see, this file contains information from http://lobid.org/organisations. I would like to revisit my suggestion from #278 . I think it would make sense to move the description to an about page (with embedded JSON-LD) and don't show that much text on the home page...
=> Add dataset description with about.jsonld.

conf/dataset.jsonld
Just a small change. We should use `dcat:distribution` rather than `schema:distribution` because
1. it is recommended by https://www.w3.org/TR/dwbp/#metadata
2. it better fits our use case as `schema:distribution` let's you rather expect a downloadable data dump (from the description: "A downloadable form of this dataset, at a specific location, in a specific format.")
=> Adjust dataset description to follow W3C recommendation

.travis.yml, app/Global.java, app/controllers/Application.java, app/controllers/Transformation.java, app/transformation/Enrich.java, app/transformation/GeoLookupMap.java, app/transformation/TripleRematch.java, conf/log4j.xml
Improve logging and recreate data
e.printStackTrace() is considered harmful.
"If you call printStackTrace() on an exception the trace is written to System.err and it's hard to route it elsewhere (or filter it). Instead of doing this you are adviced to use a logging framework."
(Source: https://stackoverflow.com/questions/10477607/avoid-printstacktrace-use-a-logger-call-instead/10477680#10477680)
Resolves #373.
- recreate data when data is not of minimum length
- make travis to use a VM with more RAM by removing "sudo: false"
=> 373 improve logging

conf/morph-enriched.xml
"Universitätsbibliothek" was erroneously mapped to libtype:n65 ("Abteilungsbibliothek, Fachbereichsbibliothek, Institutsbibliothek (Universität)") while it should actualy be libtype:n60 ("Zentrale Universitätsbibliothek")
=> Correct mapping for DBS type "UB"

.travis.yml, conf/application.conf, cron.sh
The new pelias instance is used for geo lookups.
Also, after transformations a curl is done do check if enough there is
enough geo data for the dbs IDs. If not, a mail is send.
See #419.
=> Configure new pelias instance; check geo data size

app/views/facet_map.scala.js, app/views/location_details.scala.js
This reverts commit 2c145f09f6535fd625898553f66280e975a1f216
except the use of the image proxy and the leaflet marker.
See https://github.com/hbz/lobid/issues/421 and https://github.com/hbz/lobid-organisations/issues/430.
=> Revert "Proxy external links"

conf/application.conf
Provides a workaround for #487 but does not fix the underlying problem.
The underlying problem is that the OAI-PMH-Update process does not start the second interval since we changed the Sigel-Batch-Process.
By increasing the interval we circumvent this problem until we fix or change this problem.
=> Increasing the interval-size as workaround for #487

conf/fix-enriched.fix
Pelias seem to provide only one geodata info.
See #502
=> Delete geo-Data if lat/lon is missing #502
